rootDirectory: ./input/
repositories:
  - code: UKDS
    directory: ./UKDS/ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: DNA
    directory: ./DNA/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: APIS
    directory: ./APIS/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: FSD
    directory: ./FSD/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: GESIS
    directory: ./GESIS/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: SND
    directory: ./SND/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: DANS
    directory: ./DANS/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: AUSSDA
    directory: ./AUSSDA/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/1.0.4/profile-mono.xml
    validationGate: BASIC
  - code: ADP
    directory: ./ADP/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: NSD
    directory: ./NSD/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
  - code: ProgedoSciencesPo
    directory: ./ProgedoSciencesPo/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: UniData
    directory: ./UniData/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
  - code: CSDA
    directory: ./CSDA/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
