rootDirectory: ./input/
repositories:
  - code: UKDS
    directory: ./UKDS/ddi/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: DNA
    directory: ./DNA/oai_ddi25/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: APIS
    directory: ./APIS/oai_ddi25/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: FSD
    directory: ./FSD/oai_ddi25/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: GESIS
    directory: ./GESIS/oai_ddi25/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: SND
    directory: ./SND/oai_ddi25/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: DANS
    directory: ./DANS/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: AUSSDA
    directory: ./AUSSDA/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: ADP
    directory: ./ADP/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: NSD
    directory: ./NSD/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%201.2.2%20PROFILE/cdc_122_profile.xml
    validationGate: BASIC
  - code: ProgedoSciencesPo
    directory: ./ProgedoSciencesPo/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%202.5%20PROFILE/cdc25_profile.xml
    validationGate: BASIC
  - code: UniData
    directory: ./UniData/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%201.2.2%20PROFILE/cdc_122_profile.xml
    validationGate: BASIC
  - code: CSDA
    directory: ./CSDA/
    profile: https://bitbucket.org/cessda/cessda.metadata.profiles/raw/4390b0437dbdeac8902b65627a1d443875c797a1/CDC%201.2.2%20PROFILE/cdc_122_profile.xml
    validationGate: BASIC
