rootDirectory: ./input/
repositories:
  - code: ADP
    directory: ./ADP/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: APIS
    directory: ./APIS/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: AUSSDA
    directory: ./AUSSDA/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile-mono.xml
    validationGate: BASIC
  - code: CSDA
    directory: ./CSDA/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
  - code: DANS
    directory: ./DANS/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: DNA
    directory: ./DNA/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: FSD
    directory: ./FSD/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: GESIS
    directory: ./GESIS/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: NSD
    directory: ./NSD/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
  - code: ProgedoSciencesPo
    directory: ./ProgedoSciencesPo/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: SASD
    directory: ./SASD/oai_ddi25/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: SND
    directory: ./SND/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: SODHA
    directory: ./SODHA/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile-mono.xml
    validationGate: BASIC
  - code: SoDaNet
    directory: ./SoDaNet/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: UKDS
    directory: ./UKDS/ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-2.5/latest/profile.xml
    validationGate: BASIC
  - code: UniData
    directory: ./UniData/oai_ddi/
    profile: https://cmv.cessda.eu/profiles/cdc/ddi-1.2.2/latest/profile.xml
    validationGate: BASIC
